[package]
name = "gk1000_controller"
authors = ["vextrixes"]
description = "Simple libary to control the CZC gk1000 keyboard"
repository = "https://github.com/vextrixes/gk1000-controller"
license = "Unlicense"
version = "1.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
hidapi = "2.6.6"

[features]
access_hid_wrapper = []
preset_file_saving = []
fast_controller_experimental = []