name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies  
      run: |    
        sudo apt-get update    
        sudo apt-get install -y libudev-dev pkg-config
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
