use crate::Effects;

#[allow(dead_code)]
pub struct EffectInfo<'a> {
    name: &'a str,
    effect: Effects,
    can_set_color: bool,
    can_set_speed: bool,
    can_set_direction: DirectionPolicy,
    can_set_full_color: bool,
}

#[allow(dead_code)]
pub enum DirectionPolicy {
    None,
    Horizontal01,
    Vertical23,
}

#[allow(dead_code)]
pub const EFFECTS: [EffectInfo; 20] = [
    EffectInfo {
        name: "Static",
        effect: Effects::Static,
        can_set_color: true,
        can_set_speed: false,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "SingleOn",
        effect: Effects::SingleOn,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "SingleOff",
        effect: Effects::SingleOff,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "Glittering",
        effect: Effects::Glittering,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "Rain",
        effect: Effects::Rain,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "Colorful",
        effect: Effects::Colorful,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "Breath",
        effect: Effects::Breath,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "Spectrum",
        effect: Effects::Spectrum,
        can_set_color: false,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: false,
    },
    EffectInfo {
        name: "CentrifugalWave",
        effect: Effects::CentrifugalWave,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "VerticalWave",
        effect: Effects::VerticalWave,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::Vertical23,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "HorizontalWave",
        effect: Effects::HorizontalWave,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::Horizontal01,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "Rotating",
        effect: Effects::Rotating,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "Explosion",
        effect: Effects::Explosion,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "Launch",
        effect: Effects::Launch,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "Ripples",
        effect: Effects::Ripples,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "Snake",
        effect: Effects::Snake,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "Pulse",
        effect: Effects::Pulse,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "Tilt",
        effect: Effects::Tilt,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "Shuttle",
        effect: Effects::Shuttle,
        can_set_color: true,
        can_set_speed: true,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: true,
    },
    EffectInfo {
        name: "StaticPerKey",
        effect: Effects::StaticPerKey,
        can_set_color: false,
        can_set_speed: false,
        can_set_direction: DirectionPolicy::None,
        can_set_full_color: false,
    },
];
